-- Create Logins
CREATE LOGIN StudentUser1 WITH PASSWORD = 'StudentUser1';
CREATE LOGIN StudentUser2 WITH PASSWORD = 'StudentUser2';
CREATE LOGIN StudentUser3 WITH PASSWORD = 'StudentUser3';
CREATE LOGIN StudentUser4 WITH PASSWORD = 'StudentUser4';
CREATE LOGIN StudentUser5 WITH PASSWORD = 'StudentUser5';
CREATE LOGIN StudentUser6 WITH PASSWORD = 'StudentUser6';
CREATE LOGIN StudentUser7 WITH PASSWORD = 'StudentUser7';
CREATE LOGIN StudentUser8 WITH PASSWORD = 'StudentUser8';
CREATE LOGIN StudentUser9 WITH PASSWORD = 'StudentUser9';
CREATE LOGIN StudentUser10 WITH PASSWORD = 'StudentUser10';
CREATE LOGIN StudentUser11 WITH PASSWORD = 'StudentUser11';
CREATE LOGIN StudentUser12 WITH PASSWORD = 'StudentUser12';
CREATE LOGIN StudentUser13 WITH PASSWORD = 'StudentUser13';
CREATE LOGIN StudentUser14 WITH PASSWORD = 'StudentUser14';
CREATE LOGIN StudentUser15 WITH PASSWORD = 'StudentUser15';
CREATE LOGIN StudentUser16 WITH PASSWORD = 'StudentUser16';
CREATE LOGIN StudentUser17 WITH PASSWORD = 'StudentUser17';
CREATE LOGIN StudentUser18 WITH PASSWORD = 'StudentUser18';
CREATE LOGIN StudentUser19 WITH PASSWORD = 'StudentUser19';
CREATE LOGIN StudentUser20 WITH PASSWORD = 'StudentUser20';
CREATE LOGIN StudentUser21 WITH PASSWORD = 'StudentUser21';
CREATE LOGIN StudentUser22 WITH PASSWORD = 'StudentUser22';
CREATE LOGIN StudentUser23 WITH PASSWORD = 'StudentUser23';
CREATE LOGIN StudentUser24 WITH PASSWORD = 'StudentUser24';
CREATE LOGIN StudentUser25 WITH PASSWORD = 'StudentUser25';
CREATE LOGIN StudentUser26 WITH PASSWORD = 'StudentUser26';
CREATE LOGIN StudentUser27 WITH PASSWORD = 'StudentUser27';
CREATE LOGIN StudentUser28 WITH PASSWORD = 'StudentUser28';
CREATE LOGIN StudentUser29 WITH PASSWORD = 'StudentUser29';
CREATE LOGIN StudentUser30 WITH PASSWORD = 'StudentUser30';
CREATE LOGIN PlacementHead WITH PASSWORD = 'PlacementHead';
CREATE LOGIN HOD WITH PASSWORD = 'HOD';
CREATE LOGIN Dean WITH PASSWORD = 'Dean';
CREATE LOGIN CareerCounselor WITH PASSWORD = 'CareerCounselor';
CREATE LOGIN FacultyAdvisor WITH PASSWORD = 'FacultyAdvisor';

-- Create Users
CREATE USER StudentUser1 FOR LOGIN StudentUser1;
CREATE USER StudentUser2 FOR LOGIN StudentUser2;
CREATE USER StudentUser3 FOR LOGIN StudentUser3;
CREATE USER StudentUser4 FOR LOGIN StudentUser4;
CREATE USER StudentUser5 FOR LOGIN StudentUser5;
CREATE USER StudentUser6 FOR LOGIN StudentUser6;
CREATE USER StudentUser7 FOR LOGIN StudentUser7;
CREATE USER StudentUser8 FOR LOGIN StudentUser8;
CREATE USER StudentUser9 FOR LOGIN StudentUser9;
CREATE USER StudentUser10 FOR LOGIN StudentUser10;
CREATE USER StudentUser11 FOR LOGIN StudentUser11;
CREATE USER StudentUser12 FOR LOGIN StudentUser12;
CREATE USER StudentUser13 FOR LOGIN StudentUser13;
CREATE USER StudentUser14 FOR LOGIN StudentUser14;
CREATE USER StudentUser15 FOR LOGIN StudentUser15;
CREATE USER StudentUser16 FOR LOGIN StudentUser16;
CREATE USER StudentUser17 FOR LOGIN StudentUser17;
CREATE USER StudentUser18 FOR LOGIN StudentUser18;
CREATE USER StudentUser19 FOR LOGIN StudentUser19;
CREATE USER StudentUser20 FOR LOGIN StudentUser20;
CREATE USER StudentUser21 FOR LOGIN StudentUser21;
CREATE USER StudentUser22 FOR LOGIN StudentUser22;
CREATE USER StudentUser23 FOR LOGIN StudentUser23;
CREATE USER StudentUser24 FOR LOGIN StudentUser24;
CREATE USER StudentUser25 FOR LOGIN StudentUser25;
CREATE USER StudentUser26 FOR LOGIN StudentUser26;
CREATE USER StudentUser27 FOR LOGIN StudentUser27;
CREATE USER StudentUser28 FOR LOGIN StudentUser28;
CREATE USER StudentUser29 FOR LOGIN StudentUser29;
CREATE USER StudentUser30 FOR LOGIN StudentUser30;
CREATE USER PlacementHead FOR LOGIN PlacementHead;
CREATE USER HOD FOR LOGIN HOD;
CREATE USER Dean FOR LOGIN Dean;
CREATE USER CareerCounselor FOR LOGIN CareerCounselor;
CREATE USER FacultyAdvisor FOR LOGIN FacultyAdvisor;

-- Roles and Permissions
CREATE ROLE StudentsRole;
GRANT SELECT ON dbo.Students TO StudentsRole;
GRANT SELECT ON dbo.ResumeVersions TO StudentsRole;
GRANT SELECT ON dbo.JobApplications TO StudentsRole;
GRANT SELECT ON dbo.Interviews TO StudentsRole;
GRANT SELECT ON dbo.FollowUps TO StudentsRole;

EXEC sp_addrolemember 'StudentsRole', 'StudentUser1';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser2';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser3';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser4';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser5';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser6';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser7';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser8';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser9';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser10';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser11';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser12';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser13';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser14';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser15';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser16';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser17';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser18';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser19';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser20';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser21';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser22';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser23';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser24';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser25';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser26';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser27';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser28';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser29';
EXEC sp_addrolemember 'StudentsRole', 'StudentUser30';

CREATE ROLE FacultyRole;
GRANT SELECT, INSERT, UPDATE ON dbo.Students TO FacultyRole;
GRANT SELECT, INSERT, UPDATE ON dbo.ResumeVersions TO FacultyRole;
GRANT SELECT, INSERT, UPDATE ON dbo.JobApplications TO FacultyRole;
GRANT SELECT, INSERT, UPDATE ON dbo.Interviews TO FacultyRole;
GRANT SELECT, INSERT, UPDATE ON dbo.FollowUps TO FacultyRole;
GRANT DELETE ON dbo.JobApplications TO FacultyRole;

EXEC sp_addrolemember 'FacultyRole', 'PlacementHead';
EXEC sp_addrolemember 'FacultyRole', 'HOD';
EXEC sp_addrolemember 'FacultyRole', 'Dean';
EXEC sp_addrolemember 'FacultyRole', 'CareerCounselor';
EXEC sp_addrolemember 'FacultyRole', 'FacultyAdvisor';
GO
